@extends('layouts.app')
@section('title', 'Transaction Detail')
@section('content')
<div class="container-fluid"><div class="d-flex justify-content-between align-items-center mb-4"><h1 class="h3">Transaction Detail</h1><a href="{{ route('transactions.index') }}" class="btn btn-secondary"><i class="fas fa-arrow-left"></i> Back</a></div>
<div class="card shadow-sm mb-4"><div class="card-header d-flex justify-content-between"><strong>Transaction Information</strong><a href="{{ route('transactions.edit', $transaction) }}" class="btn btn-sm btn-outline-primary"><i class="fas fa-edit"></i> Edit</a></div><div class="card-body"><div class="row g-3"><div class="col-md-3"><small class="text-muted">Transaction Date</small><div>{{ $transaction->transaction_date->format('d M Y') }}</div></div><div class="col-md-3"><small class="text-muted">Posted Date</small><div>{{ $transaction->posted_date->format('d M Y') }}</div></div><div class="col-md-3"><small class="text-muted">Bank</small><div>{{ $transaction->bank->name }}</div></div><div class="col-md-3"><small class="text-muted">Amount</small><div class="{{ $transaction->debit > 0 ? 'text-danger' : 'text-success' }}">RM {{ number_format($transaction->debit ?: $transaction->credit, 2) }}</div></div><div class="col-12"><small class="text-muted">Description</small><div>{{ $transaction->transaction_detail }}</div></div></div></div></div>
@if($transaction->carExpense)<div class="card shadow-sm"><div class="card-header d-flex justify-content-between"><strong><i class="fas fa-car text-warning me-1"></i>Car Maintenance</strong><a href="{{ route('car-expenses.show', $transaction->carExpense) }}" class="btn btn-sm btn-outline-primary">Open record</a></div><div class="card-body"><div class="row"><div class="col-md-4"><strong>Vehicle:</strong> {{ $transaction->carExpense->vehicle->display_name }}</div><div class="col-md-4"><strong>Mileage:</strong> {{ $transaction->carExpense->odometer ? number_format($transaction->carExpense->odometer) . ' km' : '-' }}</div><div class="col-md-4"><strong>Items:</strong> {{ $transaction->carExpense->items->count() }}</div></div></div></div>@else<div class="card shadow-sm"><div class="card-header"><strong>Car Maintenance</strong></div><div class="card-body"><div class="form-check"><input class="form-check-input" type="checkbox" id="is_car_expense"><label class="form-check-label" for="is_car_expense">This is a Car Expense</label></div><div id="car-expense-panel" class="mt-3" style="display:none"><p class="text-muted">Add the vehicle, workshop, mileage, and maintenance items for this transaction.</p><a href="{{ route('car-expenses.create', ['transaction_id' => $transaction->id]) }}" class="btn btn-warning"><i class="fas fa-car me-1"></i> Open Car Maintenance Form</a></div></div></div>@endif
</div>
@if(!$transaction->carExpense) @push('scripts')<script>document.getElementById('is_car_expense').addEventListener('change', function () { document.getElementById('car-expense-panel').style.display = this.checked ? 'block' : 'none'; });</script>@endpush @endif
@endsection
