@extends('layouts.app')
@section('title', $vehicle->exists ? 'Edit Vehicle' : 'Add Vehicle')
@section('content')
<div class="container-fluid"><div class="row justify-content-center"><div class="col-lg-8">
<div class="d-flex justify-content-between align-items-center mb-4"><h1 class="h3">{{ $vehicle->exists ? 'Edit Vehicle' : 'Add Vehicle' }}</h1><a href="{{ route('vehicles.index') }}" class="btn btn-secondary"><i class="fas fa-arrow-left"></i> Back</a></div>
<div class="card shadow-sm"><div class="card-body">
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ $vehicle->exists ? route('vehicles.update', $vehicle) : route('vehicles.store') }}">@csrf @if($vehicle->exists) @method('PUT') @endif
<div class="row g-3"><div class="col-md-6"><label class="form-label">Vehicle Name *</label><input name="name" class="form-control" required value="{{ old('name', $vehicle->name) }}" placeholder="Myvi 1.5 AV"></div><div class="col-md-6"><label class="form-label">Plate Number</label><input name="plate_number" class="form-control" value="{{ old('plate_number', $vehicle->plate_number) }}"></div><div class="col-md-6"><label class="form-label">Manufacturer</label><input name="manufacturer" class="form-control" value="{{ old('manufacturer', $vehicle->manufacturer) }}"></div><div class="col-md-6"><label class="form-label">Model</label><input name="model" class="form-control" value="{{ old('model', $vehicle->model) }}"></div><div class="col-md-6"><label class="form-label">Variant</label><input name="variant" class="form-control" value="{{ old('variant', $vehicle->variant) }}"></div><div class="col-md-3"><label class="form-label">Year</label><input type="number" name="year" class="form-control" value="{{ old('year', $vehicle->year) }}"></div><div class="col-md-3"><label class="form-label">Purchase Date</label><input type="date" name="purchase_date" class="form-control" value="{{ old('purchase_date', optional($vehicle->purchase_date)->format('Y-m-d')) }}"></div><div class="col-md-6"><label class="form-label">Current Mileage (km)</label><input type="number" name="current_odometer" min="0" class="form-control" value="{{ old('current_odometer', $vehicle->current_odometer) }}"></div><div class="col-md-6 d-flex align-items-end"><div class="form-check mb-2"><input type="checkbox" name="is_default" value="1" class="form-check-input" id="is_default" {{ old('is_default', $vehicle->is_default) ? 'checked' : '' }}><label for="is_default" class="form-check-label">Default vehicle</label></div></div></div>
<div class="mt-4"><button class="btn btn-primary"><i class="fas fa-save me-1"></i>Save Vehicle</button></div></form>
</div></div></div></div></div>
@endsection
