@extends('layouts.app')
@section('title', 'Car Maintenance Dashboard')
@section('content')
<div class="container-fluid">
<div class="d-flex justify-content-between align-items-center mb-4"><h1 class="h3 mb-0"><i class="fas fa-car text-warning me-2"></i>Car Maintenance Dashboard</h1><div><a href="{{ route('car-expenses.export') }}" class="btn btn-outline-success me-2"><i class="fas fa-file-csv me-1"></i>CSV</a><a href="{{ route('car-expenses.list') }}" class="btn btn-primary"><i class="fas fa-list me-1"></i>Maintenance List</a></div></div>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card shadow-sm border-start border-primary border-4"><div class="card-body"><div class="text-muted small">Total Maintenance Cost</div><div class="h4 mb-0">RM {{ number_format($summary['total'], 2) }}</div></div></div></div><div class="col-md-3"><div class="card shadow-sm border-start border-warning border-4"><div class="card-body"><div class="text-muted small">Cost This Month</div><div class="h4 mb-0">RM {{ number_format($summary['month'], 2) }}</div></div></div></div><div class="col-md-3"><div class="card shadow-sm border-start border-success border-4"><div class="card-body"><div class="text-muted small">Cost This Year</div><div class="h4 mb-0">RM {{ number_format($summary['year'], 2) }}</div></div></div></div><div class="col-md-3"><div class="card shadow-sm border-start border-info border-4"><div class="card-body"><div class="text-muted small">Average Service Cost</div><div class="h4 mb-0">RM {{ number_format($summary['average'], 2) }}</div></div></div></div></div>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="card shadow-sm"><div class="card-body"><div class="text-muted small">Average Cost Per KM</div><div class="h5 mb-0">RM {{ number_format($summary['average_km'], 2) }}</div></div></div></div><div class="col-md-4"><div class="card shadow-sm"><div class="card-body"><div class="text-muted small">Most Expensive Repair</div><div class="h5 mb-0">{{ $summary['most_expensive']?->workshop ?: 'No records' }}</div></div></div></div><div class="col-md-4"><div class="card shadow-sm"><div class="card-body"><div class="text-muted small">Most Expensive Amount</div><div class="h5 mb-0">RM {{ number_format($summary['most_expensive']?->total ?? 0, 2) }}</div></div></div></div></div>
<div class="row g-3 mb-4"><div class="col-lg-6"><div class="card shadow-sm"><div class="card-header">Monthly Maintenance Cost</div><div class="card-body"><canvas id="monthlyChart" height="120"></canvas></div></div></div><div class="col-lg-6"><div class="card shadow-sm"><div class="card-header">Cost by Category</div><div class="card-body"><canvas id="categoryChart" height="120"></canvas></div></div></div></div>
<div class="card shadow-sm"><div class="card-header"><strong>Upcoming Maintenance</strong></div><div class="card-body table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Vehicle</th><th>Next Service Date</th><th>Next Service Mileage</th><th>Current Mileage</th><th>Status</th></tr></thead><tbody>@forelse($upcoming as $service)<tr><td>{{ $service->vehicle->name }}</td><td>{{ $service->next_service_date?->format('d M Y') ?: '-' }}</td><td>{{ $service->next_service_km ? number_format($service->next_service_km) . ' km' : '-' }}</td><td>{{ $service->vehicle->current_odometer ? number_format($service->vehicle->current_odometer) . ' km' : '-' }}</td><td>@if($service->next_service_date && $service->next_service_date->isPast())<span class="badge bg-danger">Service Due</span>@elseif($service->next_service_km && $service->vehicle->current_odometer >= $service->next_service_km)<span class="badge bg-danger">Mileage Due</span>@else<span class="badge bg-success">Upcoming</span>@endif</td></tr>@empty<tr><td colspan="5" class="text-muted">No upcoming maintenance schedules recorded.</td></tr>@endforelse</tbody></table></div></div>
</div>
@push('scripts')<script>
new Chart(document.getElementById('monthlyChart'), {type:'bar', data:{labels:@json($monthlyTotals->keys()->values()), datasets:[{label:'RM', data:@json($monthlyTotals->values()), backgroundColor:'#f0ad4e'}]}, options:{plugins:{legend:{display:false}}, scales:{y:{beginAtZero:true}}}});
new Chart(document.getElementById('categoryChart'), {type:'doughnut', data:{labels:@json($categoryTotals->keys()->values()), datasets:[{data:@json($categoryTotals->values()), backgroundColor:['#0d6efd','#198754','#ffc107','#dc3545','#20c997','#6f42c1','#fd7e14','#6c757d']}]}, options:{plugins:{legend:{position:'bottom'}}}});
</script>@endpush
@endsection
