@extends('layouts.app')
@section('title', $expense->exists ? 'Edit Car Maintenance' : 'Add Car Maintenance')
@section('content')
<div class="container-fluid"><div class="d-flex justify-content-between align-items-center mb-4"><h1 class="h3">{{ $expense->exists ? 'Edit' : 'Add' }} Car Maintenance</h1><a href="{{ route('car-expenses.index') }}" class="btn btn-secondary"><i class="fas fa-arrow-left"></i> Back</a></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if($transaction)<div class="alert alert-info"><strong>Transaction:</strong> {{ $transaction->transaction_date->format('d M Y') }} — {{ $transaction->transaction_detail }} — RM {{ number_format($transaction->debit ?: $transaction->credit, 2) }}</div>@endif
<div class="card shadow-sm mb-4"><div class="card-body"><div class="d-flex flex-wrap gap-2 align-items-center"><strong class="me-2">Maintenance items CSV</strong><label class="btn btn-outline-secondary mb-0"><i class="fas fa-file-csv me-1"></i>Choose CSV<input type="file" id="items-csv" accept=".csv,text/csv" hidden></label><button type="button" class="btn btn-outline-secondary" id="download-csv-template"><i class="fas fa-download me-1"></i>Download CSV format</button><button type="button" class="btn btn-outline-secondary" id="export-items-csv"><i class="fas fa-file-export me-1"></i>Export current items</button><span id="items-import-status" class="small text-muted"></span></div><div class="form-text mt-2">Use the CSV format to enter items after checking your AI OCR result. Your selected transaction is saved with this form.</div></div></div>
<div class="card shadow-sm mb-4 d-none" id="csv-preview"><div class="card-header d-flex justify-content-between align-items-center"><strong>Check CSV before importing</strong><span id="csv-preview-count" class="small text-muted"></span></div><div class="card-body table-responsive"><table class="table table-sm" id="csv-preview-table"><thead></thead><tbody></tbody></table><div class="d-flex gap-2"><button type="button" class="btn btn-primary" id="use-csv-items">Use these items</button><button type="button" class="btn btn-outline-secondary" id="cancel-csv-items">Cancel</button></div></div></div>
<form id="maintenance-form" method="POST" action="{{ $expense->exists ? route('car-expenses.update', $expense) : route('car-expenses.store') }}">@csrf @if($expense->exists) @method('PUT') @endif
@php
	$selectedVehicleId = old('vehicle_id', $expense->vehicle_id ?: $vehicles->first()?->id);
	$notesData = $expense->notes_data;
	$selectedWorkshop = old('workshop_existing', $expense->workshop);
@endphp
<input type="hidden" name="transaction_id" value="{{ old('transaction_id', $transaction?->id ?? $expense->transaction_id) }}"><div class="card shadow-sm mb-4"><div class="card-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">Vehicle *</label><select name="vehicle_id" class="form-select" required><option value="">Choose vehicle</option>@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}" {{ $selectedVehicleId == $vehicle->id ? 'selected' : '' }}>{{ $vehicle->display_name }}{{ $vehicle->is_default ? ' (Default)' : '' }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Service Date *</label><input type="date" name="service_date" class="form-control" required value="{{ old('service_date', optional($expense->service_date)->format('Y-m-d')) }}"></div><div class="col-md-4"><label class="form-label">Mileage (km)</label><input type="number" name="odometer" min="0" class="form-control" value="{{ old('odometer', $expense->odometer) }}"></div><div class="col-md-4"><label class="form-label">Existing Workshop</label><select name="workshop_existing" class="form-select"><option value="">Choose existing workshop</option>@foreach($workshops as $workshop)<option value="{{ $workshop }}" {{ $selectedWorkshop === $workshop ? 'selected' : '' }}>{{ $workshop }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">New Workshop</label><input name="workshop_new" class="form-control" value="{{ old('workshop_new') }}" placeholder="Type a new workshop"></div><div class="col-md-4"><label class="form-label">Invoice Number</label><input name="invoice_number" class="form-control" value="{{ old('invoice_number', $expense->invoice_number) }}"></div><div class="col-md-4"><label class="form-label">Next Service KM</label><input type="number" name="next_service_km" class="form-control" value="{{ old('next_service_km', $expense->next_service_km) }}"></div><div class="col-md-4"><label class="form-label">Next Service Date</label><input type="date" name="next_service_date" class="form-control" value="{{ old('next_service_date', optional($expense->next_service_date)->format('Y-m-d')) }}"></div><div class="col-md-6"><label class="form-label">Note Title</label><input name="note_title" class="form-control" value="{{ old('note_title', $notesData['title']) }}" placeholder="Example: Full service and tyre replacement"></div><div class="col-md-6"><label class="form-label">Foreman / Technician</label><input name="foreman_technician" class="form-control" value="{{ old('foreman_technician', $notesData['foreman_technician']) }}" placeholder="Name of foreman or technician"></div></div></div></div>
<div class="card shadow-sm"><div class="card-header d-flex justify-content-between align-items-center"><strong>Maintenance Items</strong><button type="button" class="btn btn-sm btn-outline-primary" id="add-item"><i class="fas fa-plus"></i> Add Item</button></div><div class="card-body table-responsive"><table class="table align-middle" id="items-table"><thead><tr><th>Category</th><th>Item</th><th>Brand</th><th>Model</th><th>Qty</th><th>Unit Price</th><th>Labour</th><th>Warranty</th><th>Remarks</th><th>Total</th><th></th></tr></thead><tbody id="items-body"></tbody></table><div class="text-end h5">Grand Total: <span id="grand-total">RM 0.00</span></div></div></div>
<div class="mt-4"><button class="btn btn-primary"><i class="fas fa-save me-1"></i>Save Maintenance Record</button></div></form></div>
@php $existingItems = old('items', $expense->exists ? $expense->items->toArray() : [[]]); @endphp
@push('scripts')<script>
const categories = @json($categories); const existingItems = @json($existingItems); let itemIndex = 0;
const importStatus = document.getElementById('items-import-status');
function setImportStatus(message, isError = false) { importStatus.textContent = message; importStatus.className = `small ${isError ? 'text-danger' : 'text-muted'}`; }
function replaceItems(items) { document.getElementById('items-body').innerHTML = ''; itemIndex = 0; items.forEach(item => addItem(item)); updateTotals(); }
function parseCsv(text) { const rows = []; let row = [], value = '', quoted = false; for (let i = 0; i < text.length; i++) { const char = text[i]; if (char === '"' && text[i + 1] === '"' && quoted) { value += '"'; i++; } else if (char === '"') quoted = !quoted; else if (char === ',' && !quoted) { row.push(value); value = ''; } else if ((char === '\n' || char === '\r') && !quoted) { if (char === '\r' && text[i + 1] === '\n') i++; row.push(value); if (row.some(cell => cell.trim())) rows.push(row); row = []; value = ''; } else value += char; } if (value || row.length) { row.push(value); rows.push(row); } return rows; }
function csvValue(value) { return `"${String(value ?? '').replaceAll('"', '""')}"`; }
function itemFromCsv(headers, row) { const item = {}; headers.forEach((header, index) => { const key = header.trim().toLowerCase().replaceAll(' ', '_'); item[key] = row[index] ?? ''; }); return { category: categories.includes(item.category) ? item.category : 'Other', item_name: item.item_name || item.item || '', brand: item.brand || '', model: item.model || '', quantity: item.quantity || 1, unit_price: item.unit_price || 0, labour_cost: item.labour_cost || 0, warranty_month: item.warranty_month || '', warranty_km: item.warranty_km || '', remarks: item.remarks || '' }; }
let pendingCsvItems = [];
document.getElementById('items-csv').addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const rows = parseCsv(reader.result); if (rows.length < 2) return setImportStatus('CSV has no item rows.', true); pendingCsvItems = rows.slice(1).map(row => itemFromCsv(rows[0], row)); const preview = document.getElementById('csv-preview'); preview.classList.remove('d-none'); document.getElementById('csv-preview-count').textContent = `${pendingCsvItems.length} item(s)`; document.querySelector('#csv-preview-table thead').innerHTML = `<tr>${['Category', 'Item', 'Brand', 'Model', 'Qty', 'Unit Price', 'Labour', 'Remarks'].map(header => `<th>${header}</th>`).join('')}</tr>`; document.querySelector('#csv-preview-table tbody').innerHTML = pendingCsvItems.map(item => `<tr>${[item.category, item.item_name, item.brand, item.model, item.quantity, item.unit_price, item.labour_cost, item.remarks].map(value => `<td>${String(value ?? '').replaceAll('<', '&lt;')}</td>`).join('')}</tr>`).join(''); preview.scrollIntoView({ behavior: 'smooth', block: 'start' }); setImportStatus('Check the preview, then confirm.'); }; reader.readAsText(file); event.target.value = ''; });
document.getElementById('use-csv-items').addEventListener('click', () => { replaceItems(pendingCsvItems); document.getElementById('csv-preview').classList.add('d-none'); setImportStatus(`${pendingCsvItems.length} item(s) added to the form.`); pendingCsvItems = []; });
document.getElementById('cancel-csv-items').addEventListener('click', () => { document.getElementById('csv-preview').classList.add('d-none'); pendingCsvItems = []; setImportStatus('CSV preview cancelled.'); });
document.getElementById('download-csv-template').addEventListener('click', () => { const headers = ['category', 'item_name', 'brand', 'model', 'quantity', 'unit_price', 'labour_cost', 'warranty_month', 'warranty_km', 'remarks']; const csv = headers.join(',') + '\r\nOther,,,,1,0,0,,,Example item'; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'maintenance-items-format.csv'; link.click(); URL.revokeObjectURL(link.href); });
document.getElementById('export-items-csv').addEventListener('click', () => { const headers = ['category', 'item_name', 'brand', 'model', 'quantity', 'unit_price', 'labour_cost', 'warranty_month', 'warranty_km', 'remarks']; const rows = [...document.querySelectorAll('#items-body tr')].map(row => headers.map(key => row.querySelector(`[name$="[${key}]"]`)?.value ?? '')); const csv = [headers, ...rows].map(row => row.map(csvValue).join(',')).join('\r\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'maintenance-items.csv'; link.click(); URL.revokeObjectURL(link.href); });
function addItem(item = {}) { const i = itemIndex++; const options = categories.map(c => `<option value="${c}" ${item.category === c ? 'selected' : ''}>${c}</option>`).join(''); document.getElementById('items-body').insertAdjacentHTML('beforeend', `<tr data-row="${i}"><td><select name="items[${i}][category]" class="form-select form-select-sm" required><option value="">Choose</option>${options}</select></td><td><input name="items[${i}][item_name]" class="form-control form-control-sm" required value="${item.item_name || ''}"></td><td><input name="items[${i}][brand]" class="form-control form-control-sm" value="${item.brand || ''}"></td><td><input name="items[${i}][model]" class="form-control form-control-sm" value="${item.model || ''}"></td><td><input name="items[${i}][quantity]" type="number" min="0.01" step="0.01" class="form-control form-control-sm qty" value="${item.quantity || 1}"></td><td><input name="items[${i}][unit_price]" type="number" min="0" step="0.01" class="form-control form-control-sm price" value="${item.unit_price || 0}"></td><td><input name="items[${i}][labour_cost]" type="number" min="0" step="0.01" class="form-control form-control-sm labour" value="${item.labour_cost || 0}"></td><td><div class="d-flex gap-1"><input name="items[${i}][warranty_month]" type="number" min="0" placeholder="mo" class="form-control form-control-sm" value="${item.warranty_month || ''}"><input name="items[${i}][warranty_km]" type="number" min="0" placeholder="km" class="form-control form-control-sm" value="${item.warranty_km || ''}"></div></td><td><input name="items[${i}][remarks]" class="form-control form-control-sm" value="${item.remarks || ''}"></td><td class="row-total">RM 0.00</td><td><button type="button" class="btn btn-sm btn-outline-secondary duplicate-item" title="Duplicate row"><i class="fas fa-copy"></i></button><button type="button" class="btn btn-sm btn-outline-danger remove-item" title="Delete row"><i class="fas fa-trash"></i></button></td></tr>`); updateTotals(); }
function updateTotals() { let grand = 0; document.querySelectorAll('#items-body tr').forEach(row => { const total = (parseFloat(row.querySelector('.qty').value) || 0) * (parseFloat(row.querySelector('.price').value) || 0) + (parseFloat(row.querySelector('.labour').value) || 0); row.querySelector('.row-total').textContent = 'RM ' + total.toFixed(2); grand += total; }); document.getElementById('grand-total').textContent = 'RM ' + grand.toFixed(2); }
const transactionAmount = @json($transaction ? (float) ($transaction->debit ?: $transaction->credit) : ($expense->exists ? (float) ($expense->transaction->debit ?: $expense->transaction->credit) : null));
document.getElementById('maintenance-form').addEventListener('submit', event => { if (transactionAmount === null) return; const grandTotal = [...document.querySelectorAll('#items-body tr')].reduce((total, row) => total + ((parseFloat(row.querySelector('.qty').value) || 0) * (parseFloat(row.querySelector('.price').value) || 0)) + (parseFloat(row.querySelector('.labour').value) || 0), 0); if (Math.abs(Number(grandTotal.toFixed(2)) - Number(transactionAmount.toFixed(2))) > 0.001) { event.preventDefault(); alert(`Value not same. Transaction: RM ${transactionAmount.toFixed(2)}; Grand Total: RM ${grandTotal.toFixed(2)}.`); } });
document.getElementById('add-item').addEventListener('click', () => addItem()); document.getElementById('items-body').addEventListener('input', updateTotals); document.getElementById('items-body').addEventListener('click', e => { const row = e.target.closest('tr'); if (e.target.closest('.remove-item')) { row.remove(); updateTotals(); } if (e.target.closest('.duplicate-item')) { const item = {}; row.querySelectorAll('input, select').forEach(field => { const key = field.name.match(/\[([^\]]+)\]$/)?.[1]; if (key) item[key] = field.value; }); addItem(item); } }); existingItems.forEach(item => addItem(item));
</script>@endpush
@endsection
