@extends('layouts.app')
@section('title', $expense->exists ? 'Edit Car Maintenance' : 'Add Car Maintenance')
@section('content')
<div class="container-fluid"><div class="d-flex justify-content-between align-items-center mb-4"><h1 class="h3">{{ $expense->exists ? 'Edit' : 'Add' }} Car Maintenance</h1><a href="{{ route('car-expenses.index') }}" class="btn btn-secondary"><i class="fas fa-arrow-left"></i> Back</a></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if($transaction)<div class="alert alert-info"><strong>Transaction:</strong> {{ $transaction->transaction_date->format('d M Y') }} — {{ $transaction->transaction_detail }} — RM {{ number_format($transaction->debit ?: $transaction->credit, 2) }}</div>@endif
<form method="POST" action="{{ $expense->exists ? route('car-expenses.update', $expense) : route('car-expenses.store') }}">@csrf @if($expense->exists) @method('PUT') @endif
@php
	$selectedVehicleId = old('vehicle_id', $expense->vehicle_id ?: $vehicles->firstWhere('is_default', true)?->id);
	$notesData = $expense->notes_data;
	$selectedWorkshop = old('workshop_existing', $expense->workshop);
@endphp
<input type="hidden" name="transaction_id" value="{{ old('transaction_id', $transaction?->id ?? $expense->transaction_id) }}"><div class="card shadow-sm mb-4"><div class="card-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">Vehicle *</label><select name="vehicle_id" class="form-select" required><option value="">Choose vehicle</option>@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}" {{ $selectedVehicleId == $vehicle->id ? 'selected' : '' }}>{{ $vehicle->display_name }}{{ $vehicle->is_default ? ' (Default)' : '' }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Service Date *</label><input type="date" name="service_date" class="form-control" required value="{{ old('service_date', optional($expense->service_date)->format('Y-m-d')) }}"></div><div class="col-md-4"><label class="form-label">Mileage (km)</label><input type="number" name="odometer" min="0" class="form-control" value="{{ old('odometer', $expense->odometer) }}"></div><div class="col-md-4"><label class="form-label">Existing Workshop</label><select name="workshop_existing" class="form-select"><option value="">Choose existing workshop</option>@foreach($workshops as $workshop)<option value="{{ $workshop }}" {{ $selectedWorkshop === $workshop ? 'selected' : '' }}>{{ $workshop }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">New Workshop</label><input name="workshop_new" class="form-control" value="{{ old('workshop_new') }}" placeholder="Type a new workshop"></div><div class="col-md-4"><label class="form-label">Invoice Number</label><input name="invoice_number" class="form-control" value="{{ old('invoice_number', $expense->invoice_number) }}"></div><div class="col-md-4"><label class="form-label">Next Service KM</label><input type="number" name="next_service_km" class="form-control" value="{{ old('next_service_km', $expense->next_service_km) }}"></div><div class="col-md-4"><label class="form-label">Next Service Date</label><input type="date" name="next_service_date" class="form-control" value="{{ old('next_service_date', optional($expense->next_service_date)->format('Y-m-d')) }}"></div><div class="col-md-6"><label class="form-label">Note Title</label><input name="note_title" class="form-control" value="{{ old('note_title', $notesData['title']) }}" placeholder="Example: Full service and tyre replacement"></div><div class="col-md-6"><label class="form-label">Foreman / Technician</label><input name="foreman_technician" class="form-control" value="{{ old('foreman_technician', $notesData['foreman_technician']) }}" placeholder="Name of foreman or technician"></div></div></div></div>
<div class="card shadow-sm"><div class="card-header d-flex justify-content-between align-items-center"><strong>Maintenance Items</strong><button type="button" class="btn btn-sm btn-outline-primary" id="add-item"><i class="fas fa-plus"></i> Add Item</button></div><div class="card-body table-responsive"><table class="table align-middle" id="items-table"><thead><tr><th>Category</th><th>Item</th><th>Brand</th><th>Model</th><th>Qty</th><th>Unit Price</th><th>Labour</th><th>Warranty</th><th>Remarks</th><th>Total</th><th></th></tr></thead><tbody id="items-body"></tbody></table><div class="text-end h5">Grand Total: <span id="grand-total">RM 0.00</span></div></div></div>
<div class="mt-4"><button class="btn btn-primary"><i class="fas fa-save me-1"></i>Save Maintenance Record</button></div></form></div>
@php $existingItems = old('items', $expense->exists ? $expense->items->toArray() : [[]]); @endphp
@push('scripts')<script>
const categories = @json($categories); const existingItems = @json($existingItems); let itemIndex = 0;
function addItem(item = {}) { const i = itemIndex++; const options = categories.map(c => `<option value="${c}" ${item.category === c ? 'selected' : ''}>${c}</option>`).join(''); document.getElementById('items-body').insertAdjacentHTML('beforeend', `<tr data-row="${i}"><td><select name="items[${i}][category]" class="form-select form-select-sm" required><option value="">Choose</option>${options}</select></td><td><input name="items[${i}][item_name]" class="form-control form-control-sm" required value="${item.item_name || ''}"></td><td><input name="items[${i}][brand]" class="form-control form-control-sm" value="${item.brand || ''}"></td><td><input name="items[${i}][model]" class="form-control form-control-sm" value="${item.model || ''}"></td><td><input name="items[${i}][quantity]" type="number" min="0.01" step="0.01" class="form-control form-control-sm qty" value="${item.quantity || 1}"></td><td><input name="items[${i}][unit_price]" type="number" min="0" step="0.01" class="form-control form-control-sm price" value="${item.unit_price || 0}"></td><td><input name="items[${i}][labour_cost]" type="number" min="0" step="0.01" class="form-control form-control-sm labour" value="${item.labour_cost || 0}"></td><td><div class="d-flex gap-1"><input name="items[${i}][warranty_month]" type="number" min="0" placeholder="mo" class="form-control form-control-sm" value="${item.warranty_month || ''}"><input name="items[${i}][warranty_km]" type="number" min="0" placeholder="km" class="form-control form-control-sm" value="${item.warranty_km || ''}"></div></td><td><input name="items[${i}][remarks]" class="form-control form-control-sm" value="${item.remarks || ''}"></td><td class="row-total">RM 0.00</td><td><button type="button" class="btn btn-sm btn-outline-secondary duplicate-item" title="Duplicate row"><i class="fas fa-copy"></i></button><button type="button" class="btn btn-sm btn-outline-danger remove-item" title="Delete row"><i class="fas fa-trash"></i></button></td></tr>`); updateTotals(); }
function updateTotals() { let grand = 0; document.querySelectorAll('#items-body tr').forEach(row => { const total = (parseFloat(row.querySelector('.qty').value) || 0) * (parseFloat(row.querySelector('.price').value) || 0) + (parseFloat(row.querySelector('.labour').value) || 0); row.querySelector('.row-total').textContent = 'RM ' + total.toFixed(2); grand += total; }); document.getElementById('grand-total').textContent = 'RM ' + grand.toFixed(2); }
document.getElementById('add-item').addEventListener('click', () => addItem()); document.getElementById('items-body').addEventListener('input', updateTotals); document.getElementById('items-body').addEventListener('click', e => { const row = e.target.closest('tr'); if (e.target.closest('.remove-item')) { row.remove(); updateTotals(); } if (e.target.closest('.duplicate-item')) { const item = {}; row.querySelectorAll('input, select').forEach(field => { const key = field.name.match(/\[([^\]]+)\]$/)?.[1]; if (key) item[key] = field.value; }); addItem(item); } }); existingItems.forEach(item => addItem(item));
</script>@endpush
@endsection
