@extends('layouts.app')
@section('title', 'Car Maintenance')
@section('content')
<div class="container-fluid">
<div class="d-flex justify-content-between align-items-center mb-4"><h1 class="h3 mb-0"><i class="fas fa-car text-warning me-2"></i>Car Maintenance</h1><div><a href="{{ route('car-expenses.export') }}" class="btn btn-outline-success me-2"><i class="fas fa-file-csv me-1"></i>CSV</a><button type="button" onclick="window.print()" class="btn btn-outline-secondary me-2"><i class="fas fa-print me-1"></i>Print</button><a href="{{ route('vehicles.index') }}" class="btn btn-outline-secondary me-2"><i class="fas fa-cars me-1"></i>Vehicles</a><a href="{{ route('car-expenses.create') }}" class="btn btn-primary"><i class="fas fa-plus me-1"></i>Add Record</a></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@php($showList = request()->hasAny(['search', 'item_name', 'vehicle_id', 'year', 'category', 'workshop', 'brand', 'date_from', 'date_to', 'odometer_from', 'odometer_to', 'price_from', 'price_to']))
<ul class="nav nav-tabs mb-4" role="tablist"><li class="nav-item" role="presentation"><button class="nav-link {{ $showList ? '' : 'active' }}" data-bs-toggle="tab" data-bs-target="#dashboard-tab" type="button" role="tab">Dashboard</button></li><li class="nav-item" role="presentation"><button class="nav-link {{ $showList ? 'active' : '' }}" data-bs-toggle="tab" data-bs-target="#list-tab" type="button" role="tab">List</button></li></ul>
<div class="tab-content"><div class="tab-pane fade {{ $showList ? '' : 'show active' }}" id="dashboard-tab" role="tabpanel">
<style>#dashboard-tab > .card.shadow-sm.mb-4:has(form.row.g-2) { display: none; }</style>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card shadow-sm border-start border-primary border-4"><div class="card-body"><div class="text-muted small">Total Maintenance Cost</div><div class="h4 mb-0">RM {{ number_format($summary['total'], 2) }}</div></div></div></div><div class="col-md-3"><div class="card shadow-sm border-start border-warning border-4"><div class="card-body"><div class="text-muted small">Cost This Month</div><div class="h4 mb-0">RM {{ number_format($summary['month'], 2) }}</div></div></div></div><div class="col-md-3"><div class="card shadow-sm border-start border-success border-4"><div class="card-body"><div class="text-muted small">Cost This Year</div><div class="h4 mb-0">RM {{ number_format($summary['year'], 2) }}</div></div></div></div><div class="col-md-3"><div class="card shadow-sm border-start border-info border-4"><div class="card-body"><div class="text-muted small">Average Service Cost</div><div class="h4 mb-0">RM {{ number_format($summary['average'], 2) }}</div></div></div></div></div>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="card shadow-sm"><div class="card-body"><div class="text-muted small">Average Cost Per KM</div><div class="h5 mb-0">RM {{ number_format($summary['average_km'], 2) }}</div></div></div></div><div class="col-md-4"><div class="card shadow-sm"><div class="card-body"><div class="text-muted small">Most Expensive Repair</div><div class="h5 mb-0">{{ $summary['most_expensive']?->workshop ?: 'No records' }}</div></div></div></div><div class="col-md-4"><div class="card shadow-sm"><div class="card-body"><div class="text-muted small">Most Expensive Amount</div><div class="h5 mb-0">RM {{ number_format($summary['most_expensive']?->total ?? 0, 2) }}</div></div></div></div></div>
<div class="card shadow-sm mb-4"><div class="card-body"><form class="row g-2"><div class="col-md-2"><select name="vehicle_id" class="form-select"><option value="">All Vehicles</option>@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}" {{ request('vehicle_id') == $vehicle->id ? 'selected' : '' }}>{{ $vehicle->name }}</option>@endforeach</select></div><div class="col-md-2"><select name="year" class="form-select"><option value="">All Years</option>@foreach($years as $year)<option {{ request('year') == $year ? 'selected' : '' }}>{{ $year }}</option>@endforeach</select></div><div class="col-md-2"><select name="category" class="form-select"><option value="">All Categories</option>@foreach(\App\Http\Controllers\CarExpenseController::CATEGORIES as $category)<option {{ request('category') == $category ? 'selected' : '' }}>{{ $category }}</option>@endforeach</select></div><div class="col-md-2"><input name="workshop" class="form-control" placeholder="Workshop" value="{{ request('workshop') }}"></div><div class="col-md-2"><input name="brand" class="form-control" placeholder="Brand" value="{{ request('brand') }}"></div><div class="col-md-2"><input name="search" class="form-control" placeholder="Search" value="{{ request('search') }}"></div><div class="col-md-2"><input name="date_from" type="date" class="form-control" value="{{ request('date_from') }}"></div><div class="col-md-2"><input name="date_to" type="date" class="form-control" value="{{ request('date_to') }}"></div><div class="col-md-2"><input name="odometer_from" type="number" class="form-control" placeholder="Min km" value="{{ request('odometer_from') }}"></div><div class="col-md-2"><input name="odometer_to" type="number" class="form-control" placeholder="Max km" value="{{ request('odometer_to') }}"></div><div class="col-md-2"><input name="price_from" type="number" step="0.01" class="form-control" placeholder="Min RM" value="{{ request('price_from') }}"></div><div class="col-md-2"><input name="price_to" type="number" step="0.01" class="form-control" placeholder="Max RM" value="{{ request('price_to') }}"></div><div class="col-md-2"><button class="btn btn-primary w-100">Filter</button></div></form></div></div>
<div class="row g-3 mb-4"><div class="col-lg-6"><div class="card shadow-sm"><div class="card-header">Monthly Maintenance Cost</div><div class="card-body"><canvas id="monthlyChart" height="120"></canvas></div></div></div><div class="col-lg-6"><div class="card shadow-sm"><div class="card-header">Cost by Category</div><div class="card-body"><canvas id="categoryChart" height="120"></canvas></div></div></div></div>
<div class="card shadow-sm mb-4"><div class="card-header"><strong>Upcoming Maintenance</strong></div><div class="card-body table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Vehicle</th><th>Next Service Date</th><th>Next Service Mileage</th><th>Current Mileage</th><th>Status</th></tr></thead><tbody>@forelse($upcoming as $service)<tr><td>{{ $service->vehicle->name }}</td><td>{{ $service->next_service_date?->format('d M Y') ?: '-' }}</td><td>{{ $service->next_service_km ? number_format($service->next_service_km) . ' km' : '-' }}</td><td>{{ $service->vehicle->current_odometer ? number_format($service->vehicle->current_odometer) . ' km' : '-' }}</td><td>@if($service->next_service_date && $service->next_service_date->isPast())<span class="badge bg-danger">Service Due</span>@elseif($service->next_service_km && $service->vehicle->current_odometer >= $service->next_service_km)<span class="badge bg-danger">Mileage Due</span>@else<span class="badge bg-success">Upcoming</span>@endif</td></tr>@empty<tr><td colspan="5" class="text-muted">No upcoming maintenance schedules recorded.</td></tr>@endforelse</tbody></table></div></div>
</div><div class="tab-pane fade {{ $showList ? 'show active' : '' }}" id="list-tab" role="tabpanel">
<form method="GET" class="card shadow-sm mb-4"><div class="card-body row g-2 align-items-center"><div class="col-md-6"><input name="search" list="item-name-options" class="form-control" placeholder="Search item text" value="{{ request('search') }}"><datalist id="item-name-options">@foreach($itemNames as $itemName)<option value="{{ $itemName }}"></option>@endforeach</datalist></div><div class="col-md-auto"><button class="btn btn-primary">Search</button></div><div class="col-md-auto"><a href="{{ route('car-expenses.index') }}" class="btn btn-link">Clear</a></div></div></form>
<div class="card shadow-sm"><div class="card-body table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Date</th><th>Vehicle</th><th>Workshop</th><th>Mileage</th><th>Items</th><th class="text-end">Total</th><th></th></tr></thead><tbody>@forelse($expenses as $expense)<tr><td>{{ $expense->service_date->format('d M Y') }}</td><td>{{ $expense->vehicle->name }}</td><td>{{ $expense->workshop ?: '-' }}</td><td>{{ $expense->odometer ? number_format($expense->odometer) . ' km' : '-' }}</td><td>{{ $expense->items->pluck('item_name')->join(', ') }}</td><td class="text-end">RM {{ number_format($expense->total, 2) }}</td><td><a href="{{ route('car-expenses.show', $expense) }}" class="btn btn-sm btn-outline-primary"><i class="fas fa-eye"></i></a></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">No car maintenance records found.</td></tr>@endforelse</tbody></table><div>{{ $expenses->links() }}</div></div></div>
@if(request()->filled('search'))
<div class="card shadow-sm mt-3"><div class="card-body table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Category</th><th>Item</th><th>Brand / Model</th><th>Qty</th><th>Unit</th><th>Labour</th><th>Total</th><th>Warranty</th></tr></thead><tbody>@foreach($expenses as $expense)@foreach($expense->items as $item)<tr><td>{{ $item->category }}</td><td>{{ $item->item_name }}</td><td>{{ trim(($item->brand ?: '') . ' ' . ($item->model ?: '')) ?: '-' }}</td><td>{{ number_format((float) $item->quantity, 2) }}</td><td>RM {{ number_format((float) $item->unit_price, 2) }}</td><td>RM {{ number_format((float) $item->labour_cost, 2) }}</td><td>RM {{ number_format((float) $item->total_price, 2) }}</td><td>{{ $item->warranty_month ? $item->warranty_month . ' months' : '-' }}</td></tr>@endforeach @endforeach</tbody></table></div></div>
@endif
</div></div>
</div>
@push('scripts')<script>
new Chart(document.getElementById('monthlyChart'), {type:'bar', data:{labels:@json($monthlyTotals->keys()->values()), datasets:[{label:'RM', data:@json($monthlyTotals->values()), backgroundColor:'#f0ad4e'}]}, options:{plugins:{legend:{display:false}}, scales:{y:{beginAtZero:true}}}});
new Chart(document.getElementById('categoryChart'), {type:'doughnut', data:{labels:@json($categoryTotals->keys()->values()), datasets:[{data:@json($categoryTotals->values()), backgroundColor:['#0d6efd','#198754','#ffc107','#dc3545','#20c997','#6f42c1','#fd7e14','#6c757d']}]}, options:{plugins:{legend:{position:'bottom'}}}});
</script>@endpush
@endsection
