@extends('layouts.app')
@section('title', 'Maintenance List')
@section('content')
<div class="container-fluid">
<div class="d-flex justify-content-between align-items-center mb-4"><h1 class="h3 mb-0"><i class="fas fa-list text-warning me-2"></i>Maintenance List</h1><div><a href="{{ route('car-expenses.index') }}" class="btn btn-outline-secondary me-2"><i class="fas fa-chart-pie me-1"></i>Dashboard</a><a href="{{ route('car-expenses.create') }}" class="btn btn-primary"><i class="fas fa-plus me-1"></i>Add Record</a></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card shadow-sm mb-4"><div class="card-body"><form method="GET" class="row g-2 align-items-center"><div class="col-md-6"><select name="item_name" class="form-select"><option value="">All Items</option>@foreach($itemNames as $itemName)<option value="{{ $itemName }}" {{ request('item_name') === $itemName ? 'selected' : '' }}>{{ $itemName }}</option>@endforeach</select></div><div class="col-md-auto"><button class="btn btn-primary"><i class="fas fa-search me-1"></i>Search</button></div><div class="col-md-auto"><a href="{{ route('car-expenses.list') }}" class="btn btn-link">Clear</a></div></form></div></div>
<div class="card shadow-sm"><div class="card-body table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Date</th><th>Vehicle</th><th>Workshop</th><th>Mileage</th><th>Items</th><th class="text-end">Total</th><th></th></tr></thead><tbody>@forelse($expenses as $expense)<tr><td>{{ $expense->service_date->format('d/m/Y') }}</td><td>{{ $expense->vehicle->name }}</td><td>{{ $expense->workshop ?: '-' }}</td><td>{{ $expense->odometer ? number_format($expense->odometer) . ' km' : '-' }}</td><td>{{ $expense->items->pluck('item_name')->join(', ') }}</td><td class="text-end">RM {{ number_format($expense->total, 2) }}</td><td><a href="{{ route('car-expenses.show', $expense) }}" class="btn btn-sm btn-outline-primary"><i class="fas fa-eye"></i></a></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">No car maintenance records found.</td></tr>@endforelse</tbody></table><div>{{ $expenses->links() }}</div></div></div>
@if(request()->filled('search'))<div class="card shadow-sm mt-3"><div class="card-body table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Category</th><th>Item</th><th>Brand / Model</th><th>Qty</th><th>Unit</th><th>Labour</th><th>Total</th><th>Warranty</th></tr></thead><tbody>@foreach($expenses as $expense)@foreach($expense->items as $item)<tr><td>{{ $item->category }}</td><td>{{ $item->item_name }}</td><td>{{ trim(($item->brand ?: '') . ' ' . ($item->model ?: '')) ?: '-' }}</td><td>{{ number_format((float) $item->quantity, 2) }}</td><td>RM {{ number_format((float) $item->unit_price, 2) }}</td><td>RM {{ number_format((float) $item->labour_cost, 2) }}</td><td>RM {{ number_format((float) $item->total_price, 2) }}</td><td>{{ $item->warranty_month ? $item->warranty_month . ' months' : '-' }}</td></tr>@endforeach @endforeach</tbody></table></div></div>@endif
</div>
@endsection
