@extends('layouts.app')
@section('title', 'Car Maintenance Detail')
@section('content')
<div class="container-fluid"><div class="d-flex justify-content-between align-items-center mb-4"><h1 class="h3"><i class="fas fa-car text-warning me-2"></i>Maintenance Detail</h1><div><a href="{{ route('car-expenses.edit', $carExpense) }}" class="btn btn-primary"><i class="fas fa-edit me-1"></i>Edit</a><a href="{{ route('car-expenses.index') }}" class="btn btn-secondary ms-2">Back</a></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="row g-3"><div class="col-lg-4"><div class="card shadow-sm h-100"><div class="card-header">Transaction Information</div><div class="card-body"><div class="mb-2"><strong>Date:</strong> {{ $carExpense->transaction->transaction_date->format('d M Y') }}</div><div class="mb-2"><strong>Description:</strong> {{ $carExpense->transaction->transaction_detail }}</div><div class="mb-2"><strong>Amount:</strong> RM {{ number_format($carExpense->transaction->debit ?: $carExpense->transaction->credit, 2) }}</div><a href="{{ route('transactions.show', $carExpense->transaction) }}" class="btn btn-sm btn-outline-primary">View transaction</a></div></div></div><div class="col-lg-8"><div class="card shadow-sm h-100"><div class="card-header">Maintenance Information</div><div class="card-body"><div class="row g-3"><div class="col-md-4"><small class="text-muted">Vehicle</small><div>{{ $carExpense->vehicle->display_name }}</div></div><div class="col-md-4"><small class="text-muted">Service Date</small><div>{{ $carExpense->service_date->format('d M Y') }}</div></div><div class="col-md-4"><small class="text-muted">Mileage</small><div>{{ $carExpense->odometer ? number_format($carExpense->odometer) . ' km' : '-' }}</div></div><div class="col-md-4"><small class="text-muted">Workshop</small><div>{{ $carExpense->workshop ?: '-' }}</div></div><div class="col-md-4"><small class="text-muted">Invoice</small><div>{{ $carExpense->invoice_number ?: '-' }}</div></div><div class="col-md-4"><small class="text-muted">Next Service</small><div>{{ $carExpense->next_service_km ? number_format($carExpense->next_service_km) . ' km' : '-' }}</div></div><div class="col-12"><small class="text-muted d-block mb-2">Notes</small><table class="table table-sm table-bordered mb-0"><tbody><tr><th scope="row" class="w-25">Title</th><td>{{ $carExpense->notes_data['title'] ?: '-' }}</td></tr><tr><th scope="row">Foreman / Technician</th><td>{{ $carExpense->notes_data['foreman_technician'] ?: '-' }}</td></tr></tbody></table></div></div></div></div></div></div>
<div class="card shadow-sm mt-3"><div class="card-header d-flex justify-content-between"><strong>Replaced Parts and Services</strong><strong>Grand Total: RM {{ number_format($carExpense->total, 2) }}</strong></div><div class="card-body table-responsive"><table class="table"><thead><tr><th>Category</th><th>Item</th><th>Brand / Model</th><th>Qty</th><th>Unit</th><th>Labour</th><th>Total</th><th>Warranty</th></tr></thead><tbody>@foreach($carExpense->items as $item)<tr><td>{{ $item->category }}</td><td>{{ $item->item_name }}</td><td>{{ trim($item->brand . ' ' . $item->model) ?: '-' }}</td><td>{{ $item->quantity }}</td><td>RM {{ number_format($item->unit_price, 2) }}</td><td>RM {{ number_format($item->labour_cost, 2) }}</td><td>RM {{ number_format($item->total_price, 2) }}</td><td>{{ $item->warranty_month ? $item->warranty_month . ' mo' : '' }}{{ $item->warranty_km ? ' / ' . number_format($item->warranty_km) . ' km' : '' }}</td></tr>@endforeach</tbody></table></div></div>
</div>
@endsection
